# Generated by Django 3.2.24 on 2025-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dispositivo', models.CharField(max_length=100, verbose_name='Nome do Dispositivo')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='Endereço IP')),
                ('departamento', models.CharField(choices=[('TI', 'TI'), ('Financeiro', 'Financeiro'), ('RH', 'RH'), ('Marketing', 'Marketing'), ('Outro', 'Outro')], max_length=50, verbose_name='Departamento')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('contador_paginas', models.PositiveIntegerField(default=0, verbose_name='Contador de Páginas')),
            ],
        ),
    ]
