# Generated by Django 3.2.24 on 2025-05-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0002_rename_impressora_cadastroimpressora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField(verbose_name='Data da Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída')], default='Pendente', max_length=20, verbose_name='Status')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='impressoras.cadastroimpressora')),
            ],
        ),
    ]
