# Generated by Django 3.2.24 on 2025-05-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0003_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
