# Generated by Django 3.2.24 on 2025-05-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0004_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_troca', models.DateField(verbose_name='Data da Troca')),
                ('contador_paginas', models.PositiveIntegerField(default=0, verbose_name='Contador de Páginas')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_toner', to='impressoras.cadastroimpressora')),
            ],
        ),
    ]
