# Generated by Django 3.2.24 on 2025-05-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocftv',
            name='departamento',
        ),
        migrations.AddField(
            model_name='cadastrocftv',
            name='rack',
            field=models.CharField(choices=[('Sala de cabos', 'Sala de cabos'), ('Sala da TI', 'Sala da TI'), ('CMU', 'CMU'), ('Corredor CMU', 'Corredor CMU'), ('Laboratório', 'Laboratório'), ('CDU', 'CDU')], default='', max_length=50, verbose_name='Rack'),
        ),
    ]
